<?php
declare(strict_types=1);

// Generated by HESTIA Installer. No SQL provisioning credential is stored here.
// This resource only defines the five constants consumed by HESTIA get_pdo().
// It does not connect, start a session, run DDL, enable Assistant or seal install.
(static function (): void {
    $handle = null;
    try {
        foreach (['DB_HOST', 'DB_NAME', 'DB_USER', 'DB_PASS', 'DB_CHARSET'] as $constant) {
            if (defined($constant)) throw new RuntimeException('CONFIG_INVALID');
        }
        $path = hex2bin('__DATABASE_PATH_HEX__');
        if (!is_string($path) || !str_starts_with($path, '/')) throw new RuntimeException('CONFIG_INVALID');
        $parent = dirname($path);
        while (true) {
            $info = @lstat($parent);
            if (!is_array($info) || ($info['mode'] & 0170000) !== 0040000
                || $info['uid'] !== 0 || ($info['mode'] & 0022) !== 0) throw new RuntimeException('CONFIG_INVALID');
            if ($parent === '/') break;
            $parent = dirname($parent);
        }
        $before = @lstat($path);
        if (!is_array($before) || ($before['mode'] & 0170000) !== 0100000 || $before['uid'] !== 0
            || $before['gid'] !== __SERVICE_GID__ || ($before['mode'] & 07777) !== 0640
            || $before['nlink'] !== 1 || $before['size'] > 16384) throw new RuntimeException('CONFIG_INVALID');
        $handle = @fopen($path, 'rb');
        if (!is_resource($handle)) throw new RuntimeException('CONFIG_INVALID');
        $opened = fstat($handle);
        if (!is_array($opened) || $opened !== $before) throw new RuntimeException('CONFIG_INVALID');
        $raw = stream_get_contents($handle, 16385);
        if (!is_string($raw) || strlen($raw) > 16384 || strlen($raw) !== $opened['size']) throw new RuntimeException('CONFIG_INVALID');
        $after = fstat($handle);
        foreach (['dev', 'ino', 'size', 'mtime', 'ctime', 'mode', 'uid', 'gid', 'nlink'] as $field) {
            if ($after[$field] !== $opened[$field]) throw new RuntimeException('CONFIG_INVALID');
        }
        fclose($handle); $handle = null;
        $config = json_decode($raw, false, 8, JSON_THROW_ON_ERROR);
        if (!$config instanceof stdClass
            || json_encode($config, JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR) !== $raw) throw new RuntimeException('CONFIG_INVALID');
        $keys = array_keys(get_object_vars($config)); sort($keys);
        if ($keys !== ['charset', 'host', 'name', 'password', 'user', 'version'] || $config->version !== 1
            || $config->host !== '127.0.0.1' || $config->charset !== 'utf8mb4'
            || !is_string($config->name) || !preg_match('/^[A-Za-z0-9_]{1,64}$/D', $config->name)
            || in_array(strtolower($config->name), ['mysql', 'sys', 'information_schema', 'performance_schema'], true)
            || !is_string($config->user) || !preg_match('/^[A-Za-z0-9_]{1,32}$/D', $config->user)
            || strtolower($config->user) === 'root' || !is_string($config->password)
            || strlen($config->password) < 1 || strlen($config->password) > 1024
            || preg_match('//u', $config->password) !== 1 || preg_match('/\p{C}/u', $config->password)) {
            throw new RuntimeException('CONFIG_INVALID');
        }
        define('DB_HOST', $config->host); define('DB_NAME', $config->name);
        define('DB_USER', $config->user); define('DB_PASS', $config->password); define('DB_CHARSET', $config->charset);
    } catch (Throwable $exception) {
        // No original exception, raw JSON, path or password in a diagnostic.
        throw new RuntimeException('HESTIA_DATABASE_CONFIG_INVALID');
    } finally {
        if (is_resource($handle)) fclose($handle);
    }
})();
