#!/usr/bin/env python3
"""Strict, dependency-free Quality tooling. Never imported by the installer runtime."""
from __future__ import annotations

import argparse
import ast
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import platform
import re
import shutil
import stat
import subprocess
import sys
import time
import unittest
import xml.etree.ElementTree as ET
import zipfile

ROOT = Path(__file__).resolve().parents[1]
EXCLUDED = {'.git', '__pycache__', '.venv', 'venv', 'quality-results', 'dist', 'build', '.pytest_cache'}
REQUIRED = ('install-hestia.sh', 'installer/__main__.py', 'installer/web/index.html',
            'installer/web/bootstrap.html', 'installer/web/assets/hestia-hero.webp',
            'scripts/quality-local.sh', 'scripts/quality-wizard.sh', 'tests/quality-baseline.json')


class QualityError(RuntimeError):
    pass


def encode(value: object) -> bytes:
    return (json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2) + '\n').encode('utf-8')


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def safe_name(name: str) -> bool:
    path = PurePosixPath(name)
    return bool(name) and not path.is_absolute() and '..' not in path.parts and '\\' not in name and not any(ord(c) < 32 for c in name) and str(path) == name


def files(root: Path = ROOT) -> list[str]:
    # A checkout uses exactly the index file set. Extracted source archives work
    # without git, but may not include a venv, results, or generated bytecode.
    if (root / '.git').exists():
        result = subprocess.run(['git', '-C', str(root), 'ls-files', '-z'], check=True, capture_output=True)
        names = result.stdout.decode('utf-8').rstrip('\0').split('\0')
    else:
        names = [p.relative_to(root).as_posix() for p in root.rglob('*')
                 if not any(part in EXCLUDED for part in p.relative_to(root).parts)
                 and (p.is_file() or p.is_symlink()) and p.suffix not in {'.pyc', '.log'}]
    if not names or any(not safe_name(n) for n in names):
        raise QualityError('Unsafe or empty source file set')
    for name in names:
        path = root / name
        if path.is_symlink() or not path.is_file():
            raise QualityError('Missing or linked source file: ' + name)
        if any(p.is_symlink() for p in path.parents if p != root and root in p.parents):
            raise QualityError('Linked source directory: ' + name)
    return sorted(names)


def snapshot(root: Path = ROOT) -> dict:
    return {name: {'sha256': digest((root / name).read_bytes()),
                   'mode': format(stat.S_IMODE((root / name).stat().st_mode), '04o')}
            for name in files(root)}


def verify_snapshot(expected: dict, root: Path = ROOT) -> None:
    if snapshot(root) != expected:
        raise QualityError('Sources or executable modes changed after the Quality snapshot')


def is_docs_only(names: list[str]) -> bool:
    if not names:
        return False
    return all(safe_name(n) and (n in {'README.md', 'CONTRIBUTING.md'} or
               (n.startswith('docs/') and n.endswith('.md'))) for n in names)


def scope() -> bool:
    base = os.environ.get('QUALITY_BASE', '')
    if os.environ.get('GITHUB_EVENT_NAME') == 'workflow_dispatch' or not re.fullmatch(r'[0-9a-f]{40}', base) or set(base) == {'0'}:
        return True
    try:
        result = subprocess.run(['git', 'diff', '--name-only', '-z', base, 'HEAD'], cwd=ROOT,
                                check=True, capture_output=True)
        names = result.stdout.decode('utf-8').rstrip('\0').split('\0')
        return not is_docs_only(names)
    except (subprocess.CalledProcessError, UnicodeError):
        return True  # Missing history must not disable tests.


def python_risks(text: str) -> list[str]:
    tree = ast.parse(text)
    risks = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        name = ast.unparse(node.func)
        if name in {'eval', 'exec', 'os.system', 'os.popen', 'pickle.loads', 'pickle.load', 'ssl._create_unverified_context'}:
            risks.append(f'{node.lineno}: forbidden runtime call {name}')
        for kw in node.keywords:
            if kw.arg == 'shell' and not (isinstance(kw.value, ast.Constant) and kw.value.value is False):
                risks.append(f'{node.lineno}: shell execution is forbidden')
    return risks


def static(root: Path = ROOT) -> None:
    names = files(root)
    missing = sorted(set(REQUIRED) - set(names))
    if missing:
        raise QualityError('Required source files missing: ' + ', '.join(missing))
    for tool in ('node', 'bash', 'python3'):
        if not shutil.which(tool):
            raise QualityError('Required Quality tool missing: ' + tool)
    errors = []
    for name in names:
        path = root / name
        data = path.read_bytes()
        mode = stat.S_IMODE(path.stat().st_mode)
        if mode & 0o022:
            errors.append(name + ': group/world writable source')
        if name.endswith('.sh'):
            if mode != 0o755:
                errors.append(name + ': expected executable mode 0755')
            subprocess.run(['bash', '-n', str(path)], check=True)
        if name.endswith('.js'):
            subprocess.run(['node', '--check', str(path)], check=True)
        if name.endswith('.py'):
            compile(data, name, 'exec')
            if name.startswith('installer/'):
                errors += [name + ': ' + item for item in python_risks(data.decode('utf-8'))]
        if b'\x00' in data:
            continue
        try:
            text = data.decode('utf-8')
        except UnicodeError:
            continue
        if re.search(r'(?:gh[pousr]_[A-Za-z0-9]{36,}|github_pat_[A-Za-z0-9_]{60,}|sk-proj-[A-Za-z0-9_-]{40,})', text):
            errors.append(name + ': possible credential (value not printed)')
        if re.search(r'-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----\s+[A-Za-z0-9+/=\s]{80,}-----END', text):
            errors.append(name + ': private key material (value not printed)')
        if name.startswith('installer/web/') and path.suffix in {'.html', '.css', '.js'}:
            if re.search(r'https?://|(?:src|href)\s*=\s*[\"\']\s*//|url\(\s*[\"\']?//', text):
                errors.append(name + ': remote runtime resource')
            if re.search(r'\b(?:localStorage|sessionStorage|indexedDB)\b', text):
                errors.append(name + ': browser persistence is forbidden')
        if path.suffix == '.md':
            if not text.strip() or not re.search(r'^# ', text, re.M):
                errors.append(name + ': empty document or missing title')
            # Validate relative local Markdown targets, not public URLs or anchors.
            for target in re.findall(r'\]\(([^\s)]+)\)', text):
                if ':' in target or target.startswith(('#', '/')):
                    continue
                candidate = (path.parent / target.split('#', 1)[0]).resolve()
                if root.resolve() not in candidate.parents or not candidate.exists():
                    errors.append(name + ': missing/unsafe local documentation target ' + target)
    workflow = root / '.github/workflows/quality.yml'
    if workflow.exists():
        text = workflow.read_text()
        if 'pull_request_target' in text or 'continue-on-error:' in text:
            errors.append('Quality workflow must not run privileged PR code or ignore errors')
        for use in re.findall(r'^\s*-?\s*uses:\s*(\S+)', text, re.M):
            if not re.fullmatch(r'actions/[a-z-]+@[0-9a-f]{40}', use):
                errors.append('Quality action is not pinned to an official immutable SHA')
    if errors:
        raise QualityError('\n'.join(errors))
    print(f'Static, source permissions, documentation and security guards: PASS ({len(names)} files)')


def flatten(suite):
    for test in suite:
        if isinstance(test, unittest.TestSuite):
            yield from flatten(test)
        else:
            yield test


def load_suite(group: str):
    sys.path.insert(0, str(ROOT))
    sys.path.insert(0, str(ROOT / 'tests'))
    if group == 'tools':
        return unittest.defaultTestLoader.loadTestsFromName('test_quality_gate.QualityGateTests')
    if group == 'core':
        return unittest.defaultTestLoader.discover(str(ROOT / 'tests'), pattern='test_*.py')
    module = 'browser_wizard' if group == 'bridge' else 'browser_native'
    cls = 'BrowserWizardTests' if group == 'bridge' else 'NativeBrowserTests'
    return unittest.defaultTestLoader.loadTestsFromName(module + '.' + cls)


def verdict(result: unittest.TestResult, missing: list[str], stable: bool) -> bool:
    return (result.testsRun > 0 and result.wasSuccessful() and not result.skipped and
            not result.expectedFailures and not result.unexpectedSuccesses and not missing and stable)


def run(group: str) -> int:
    before = snapshot()
    manifest_hash = digest(encode(before))
    out = ROOT / 'quality-results'
    out.mkdir(exist_ok=True)
    (out / 'SOURCE-MANIFEST.json').write_bytes(encode(before))
    suite = load_suite(group)
    cases = list(flatten(suite))
    ids = [t.id() for t in cases]
    required = json.loads((ROOT / 'tests/quality-baseline.json').read_text())['required_tests'][group]
    missing = sorted(set(required) - set(ids))
    started = time.monotonic()
    result = unittest.TextTestRunner(verbosity=2).run(suite)
    stable = snapshot() == before
    passed = verdict(result, missing, stable) and len(set(ids)) == len(ids)
    report = {'schema': 1, 'suite': group, 'status': 'PASS' if passed else 'FAIL',
              'tests_run': result.testsRun, 'discovered_ids': sorted(ids),
              'failures': len(result.failures), 'errors': len(result.errors),
              'skipped': len(result.skipped), 'expected_failures': len(result.expectedFailures),
              'unexpected_successes': len(result.unexpectedSuccesses), 'missing_ids': missing,
              'source_stable': stable, 'source_manifest_sha256': manifest_hash,
              'python': platform.python_version(),
              'os': platform.freedesktop_os_release().get('ID', 'unknown'),
              'os_version': platform.freedesktop_os_release().get('VERSION_ID', 'unknown'),
              'seconds': round(time.monotonic() - started, 3)}
    (out / (group + '.json')).write_bytes(encode(report))
    xml = ET.Element('testsuite', name=group, tests=str(result.testsRun),
                     failures=str(len(result.failures)), errors=str(len(result.errors)),
                     skipped=str(len(result.skipped)), time=str(report['seconds']))
    issues = {test.id(): ('failure', text) for test, text in result.failures}
    issues.update({test.id(): ('error', text) for test, text in result.errors})
    issues.update({test.id(): ('skipped', reason) for test, reason in result.skipped})
    for identifier in sorted(ids):
        cls, _, method = identifier.rpartition('.')
        item = ET.SubElement(xml, 'testcase', classname=cls, name=method)
        related = [entry for key, entry in issues.items() if key == identifier or key.startswith(identifier + ' (')]
        for kind, detail in related:
            ET.SubElement(item, kind).text = detail
    if not passed:
        item = ET.SubElement(xml, 'testcase', classname='quality', name='strict_gate')
        ET.SubElement(item, 'failure').text = 'Missing/skipped/expected-failure/duplicate tests or source drift are forbidden.'
    ET.ElementTree(xml).write(out / (group + '.xml'), encoding='utf-8', xml_declaration=True)
    print(f'HESTIA {group} strict Quality: {report["status"]}; {result.testsRun} tests; {len(missing)} missing')
    return 0 if passed else 1


def gate(code: str, selected: str, core: str, browser: str) -> None:
    if selected != 'success' or code not in {'true', 'false'}:
        raise QualityError('Quality scope/static check did not succeed')
    required = 'success' if code == 'true' else 'skipped'
    if core != required or browser != required:
        raise QualityError('Required Quality job did not succeed (or invalid docs-only scope)')
    print('Installer Quality: PASS' if code == 'true' else 'Installer Quality: PASS - documentation only; application tests not requested')


def package(reports: Path, output: Path) -> None:
    current = snapshot()
    expected_hash = digest(encode(current))
    records = []
    for path in sorted(reports.rglob('*.json')):
        if path.name not in {'core.json', 'bridge.json', 'native.json'}:
            continue
        record = json.loads(path.read_text())
        if record.get('status') != 'PASS' or not record.get('source_stable') or record.get('source_manifest_sha256') != expected_hash:
            raise QualityError('Unsuccessful or mismatched Quality evidence: ' + str(path))
        if any(record.get(key) != 0 for key in ('errors', 'failures', 'skipped', 'expected_failures', 'unexpected_successes')) or record.get('missing_ids') != [] or record.get('tests_run', 0) <= 0:
            raise QualityError('Incomplete strict Quality evidence: ' + str(path))
        records.append(record)
    cores = [r for r in records if r['suite'] == 'core']
    if len(cores) != 2 or {(r['os'], r['os_version']) for r in cores} != {('debian', '12'), ('debian', '13')} or sorted(r['suite'] for r in records) != ['bridge', 'core', 'core', 'native']:
        raise QualityError('Packaging requires both Debian versions and both browser suites')
    output.mkdir(parents=True, exist_ok=True)
    target = output / 'HESTIA-INSTALLER-QUALITY-SOURCE.zip'
    write_zip(target, current)
    verify_snapshot(current)
    (output / 'SOURCE-MANIFEST.json').write_bytes(encode(current))
    (output / 'QUALITY-SUMMARY.json').write_bytes(encode({'schema': 1, 'status': 'PASS', 'reports': records}))
    (output / 'SHA256SUMS').write_text(''.join(digest(p.read_bytes()) + '  ' + p.name + '\n' for p in sorted(output.iterdir()) if p.name != 'SHA256SUMS'), encoding='utf-8')
    print('Exact tested source package: PASS')


def write_zip(target: Path, manifest: dict, root: Path = ROOT) -> None:
    for name, entry in manifest.items():
        if not safe_name(name) or (root / name).is_symlink() or digest((root / name).read_bytes()) != entry['sha256'] or format(stat.S_IMODE((root / name).stat().st_mode), '04o') != entry['mode']:
            raise QualityError('Unsafe or changed package source: ' + name)
    with zipfile.ZipFile(target, 'w', compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for name, entry in sorted(manifest.items()):
            info = zipfile.ZipInfo(name, (2026, 1, 1, 0, 0, 0))
            info.create_system = 3
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = (stat.S_IFREG | int(entry['mode'], 8)) << 16
            archive.writestr(info, (root / name).read_bytes())
    with zipfile.ZipFile(target) as archive:
        if set(archive.namelist()) != set(manifest) or archive.testzip() is not None:
            raise QualityError('Package file-set/CRC mismatch')
        for info in archive.infolist():
            entry = manifest[info.filename]
            if digest(archive.read(info)) != entry['sha256'] or format(stat.S_IMODE(info.external_attr >> 16), '04o') != entry['mode']:
                raise QualityError('Package bytes/mode mismatch')


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subs = parser.add_subparsers(dest='command', required=True)
    subs.add_parser('static')
    subs.add_parser('scope')
    run_parser = subs.add_parser('run'); run_parser.add_argument('suite', choices=('tools', 'core', 'bridge', 'native'))
    subs.add_parser('gate')
    pack = subs.add_parser('package'); pack.add_argument('--reports', type=Path, required=True); pack.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    try:
        if args.command == 'static':
            static()
        elif args.command == 'scope':
            code = 'true' if scope() else 'false'
            print('code=' + code)
            if os.environ.get('GITHUB_OUTPUT'):
                with open(os.environ['GITHUB_OUTPUT'], 'a', encoding='utf-8') as stream:
                    stream.write('code=' + code + '\n')
        elif args.command == 'run':
            return run(args.suite)
        elif args.command == 'gate':
            gate(*(os.environ.get('QUALITY_' + key, '') for key in ('CODE', 'SCOPE_RESULT', 'CORE_RESULT', 'BROWSER_RESULT')))
        else:
            package(args.reports, args.output)
        return 0
    except (QualityError, OSError, ValueError, subprocess.CalledProcessError) as error:
        print('Quality: FAIL - ' + str(error), file=sys.stderr)
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
