from pathlib import Path

INSTALLER_NAME = "HESTIA Installer"
INSTALLER_VERSION = "0.1.0.dev0"

TEMP_PORT_MIN = 57000
TEMP_PORT_MAX = 57999
PORT_RESERVATION_ATTEMPTS = 128

DEFAULT_RUNTIME_ROOT = Path("/run/hestia-installer")
DEFAULT_STATE_ROOT = Path("/var/lib/hestia-installer")
DEFAULT_BACKUP_ROOT = Path("/root/_HestiaBCKP")

REQUIRED_BOOTSTRAP_COMMANDS = ("python3", "openssl", "ip")
SUPPORTED_DEBIAN_MAJORS = frozenset({12, 13})

BOOTSTRAP_TOKEN_TTL_SECONDS = 10 * 60
BOOTSTRAP_TOKEN_MAX_ATTEMPTS = 5
BOOTSTRAP_SESSION_TTL_SECONDS = 2 * 60 * 60
MAX_REQUEST_BODY_BYTES = 16 * 1024

SESSION_COOKIE_NAME = "HSTSESSION"
