"""Internal, maintenance-closed fragment replacement for a future public handoff.

This file primitive does not grant admission, reload systemd, start services or
enroll boot. The native coordinator must additionally fence the public workers.
It is deliberately not wired to the cockpit until that composition is qualified.
"""
from contextlib import contextmanager
import hashlib
import os
from pathlib import Path
import re
import stat

from installer import backup_files as files, database_config as fs
from installer.maintenance import MaintenanceLease
from installer.model import canonical_bytes, strict_json_loads

POLICY = 'GATEWAY_PUBLIC_FRAGMENT_TRANSFER_V1'
LIMIT = 262144
REFS = frozenset(('source_gateway', 'target_gateway', 'publication', 'shared_public',
                  'web_boot', 'mobile_boot', 'successor_code'))


class FragmentError(RuntimeError): pass


def require(value, code='GATEWAY_PUBLIC_FRAGMENT_CHANGED'):
    if not value: raise FragmentError(code)


def sha(raw): return hashlib.sha256(raw).hexdigest()


def _digest(value):
    require(type(value) is str and re.fullmatch('[a-f0-9]{64}', value))
    return value


def resources(instance):
    require(type(instance) is str and re.fullmatch('[a-f0-9]{32}', instance))
    prefix = 'hestia-' + instance
    return (prefix + '-boot-sql.service', prefix + '-boot-web.service',
            prefix + '-mobile-boot.service', prefix + '-public-http.service',
            prefix + '-public-https.service', prefix + '-public-renew.service',
            prefix + '-public-renew.timer', prefix + '-apache.service.d/60-hestia-public.conf')


def _identity(info):
    return {'device': info.st_dev, 'inode': info.st_ino}


def _file(directory, name, *, partial=False):
    handle = os.open(name, files.REGULAR, dir_fd=directory)
    try:
        info = os.fstat(handle)
        require(stat.S_ISREG(info.st_mode) and info.st_uid == info.st_gid == 0
                and info.st_nlink == 1 and stat.S_IMODE(info.st_mode) == 0o644
                and 0 <= info.st_size <= LIMIT and not os.listxattr(handle))
        raw = bytearray()
        while len(raw) <= LIMIT:
            chunk = os.read(handle, min(65536, LIMIT + 1 - len(raw)))
            if not chunk: break
            raw.extend(chunk)
        require(len(raw) == info.st_size and files._same(info, os.fstat(handle))
                and files._same(info, os.stat(name, dir_fd=directory, follow_symlinks=False)))
        require(partial or bool(raw))
        return {**_identity(info), 'bytes': len(raw), 'sha256': sha(raw)}, bytes(raw)
    finally: os.close(handle)


def _optional(directory, name):
    try: raw = files._read(directory, name, LIMIT)
    except FileNotFoundError: return None
    value = strict_json_loads(raw)
    require(type(value) is dict and canonical_bytes(value) == raw)
    return value


def _put(directory, name, value):
    old = _optional(directory, name)
    if old is None: files._new(directory, name, canonical_bytes(value))
    else: require(old == value)


class FragmentTransfer:
    """One ordered set of owned renames, pinned to the live maintenance lease.

    Callers supply generated bytes, never paths from a request. Every active
    path is derived from the instance allowlist under the system unit root.
    A temporary file without a durable inode receipt is refused, not adopted.
    """
    def __init__(self, root, unit_root, lease, references, replacements):
        require(type(lease) is MaintenanceLease, 'GATEWAY_PUBLIC_LEASE_REQUIRED')
        lease.assert_held()
        require(os.getuid() == os.geteuid() == 0, 'GATEWAY_PUBLIC_ROOT_REQUIRED')
        require(isinstance(root, Path) and isinstance(unit_root, Path)
                and root.is_absolute() and unit_root.is_absolute()
                and root.name == 'public-fragments-' + lease.lease_id)
        require(type(references) is dict and set(references) == REFS)
        for value in references.values(): _digest(value)
        require(references['source_gateway'] != references['target_gateway'])
        require(type(replacements) is dict and tuple(replacements) == resources(lease.scope.instance))
        for pair in replacements.values():
            require(type(pair) is tuple and len(pair) == 2
                    and all(type(raw) is bytes and 0 < len(raw) <= LIMIT for raw in pair)
                    and pair[0] != pair[1])
        self.root, self.unit_root, self.lease = root, unit_root, lease
        # Detach from mutable caller dictionaries.
        self.references = dict(references); self.replacements = dict(replacements)
        self.binding = {'version': 1, 'policy': POLICY, 'instance': lease.scope.instance,
                        'lease_id': lease.lease_id, 'references': self.references,
                        'unit_root': str(unit_root), 'maintenance': str(lease.scope.directory),
                        'fragments': {name: {'source': sha(pair[0]), 'target': sha(pair[1])}
                                      for name, pair in self.replacements.items()}}

    def __reduce__(self): raise TypeError('Fragment transfers cannot be serialized')

    def _held(self):
        self.lease.assert_held()
        # Pin the named maintenance directory, not only an unlinked dirfd.
        with fs._directory(self.lease.scope.directory) as fd:
            require(_identity(os.fstat(fd)) == _identity(os.fstat(self.lease._directory)))

    @contextmanager
    def _slot(self):
        self._held()
        with fs._directory(self.root) as fd:
            files._private(fd, directory=True)
            allowed = {'plan.json', *(str(i) + suffix for i in range(len(self.replacements))
                                     for suffix in ('.seed.json', '.armed.json', '.done.json'))}
            require(set(os.listdir(fd)) <= allowed)
            plan = _optional(fd, 'plan.json')
            require(plan is not None and set(plan) == {'binding', 'slot', 'directories', 'sources'}
                    and plan['binding'] == self.binding and plan['slot'] == _identity(os.fstat(fd)))
            require(type(plan['sources']) is dict and set(plan['sources']) == set(self.replacements))
            require(type(plan['directories']) is dict and set(plan['directories']) == set(self.replacements))
            for name, pair in self.replacements.items():
                row = plan['sources'][name]
                require(type(row) is dict and set(row) == {'device', 'inode', 'bytes', 'sha256'}
                        and all(type(row[k]) is int and row[k] > 0 for k in ('device', 'inode', 'bytes'))
                        and row['bytes'] == len(pair[0]) and row['sha256'] == sha(pair[0]))
                directory = plan['directories'][name]
                require(type(directory) is dict and set(directory) == {'device', 'inode'}
                        and all(type(v) is int and v > 0 for v in directory.values()))
            yield fd, plan
            self._held()
            with fs._directory(self.root) as named:
                require(_identity(os.fstat(named)) == plan['slot'])

    @contextmanager
    def _parent(self, name, plan=None):
        require(name in self.replacements)
        with fs._directory((self.unit_root / name).parent) as fd:
            info = os.fstat(fd)
            require(info.st_gid == 0 and not os.listxattr(fd))
            if plan is not None: require(_identity(info) == plan['directories'][name])
            yield fd, Path(name).name

    def prepare(self, *, confirmed):
        require(confirmed is True, 'GATEWAY_PUBLIC_CONSENT_REQUIRED'); self._held()
        sources, directories = {}, {}
        for name, (before, _) in self.replacements.items():
            with self._parent(name) as (fd, leaf):
                sources[name], raw = _file(fd, leaf)
                require(raw == before)
                fs._absent(fd, self._temporary(leaf))
                directories[name] = _identity(os.fstat(fd))
        self._held()
        with fs._directory(self.root.parent) as fd:
            files._private(fd, directory=True); fs._absent(fd, self.root.name)
            os.mkdir(self.root.name, 0o700, dir_fd=fd); os.fsync(fd)
        with fs._directory(self.root) as fd:
            files._private(fd, directory=True)
            files._new(fd, 'plan.json', canonical_bytes({'binding': self.binding,
                'slot': _identity(os.fstat(fd)), 'directories': directories, 'sources': sources}))
        return self.check()

    def _temporary(self, leaf): return '.' + leaf + '.gateway-' + self.lease.lease_id

    def _observe(self, journal, plan, index, name):
        owner = {'plan_sha256': sha(canonical_bytes(plan)), 'index': index}
        seed = _optional(journal, str(index) + '.seed.json')
        arm = _optional(journal, str(index) + '.armed.json')
        done = _optional(journal, str(index) + '.done.json')
        with self._parent(name, plan) as (fd, leaf):
            active, _ = _file(fd, leaf)
            try: pending, raw = _file(fd, self._temporary(leaf), partial=True)
            except FileNotFoundError: pending = raw = None
        source = plan['sources'][name]; target = self.replacements[name][1]
        if seed is None:
            require(arm is None and done is None and pending is None and active == source)
            return 'PENDING', owner, None
        require(set(seed) == {'owner', 'replacement'} and seed['owner'] == owner)
        identity = seed['replacement']
        require(type(identity) is dict and set(identity) == {'device', 'inode'}
                and all(type(v) is int and v > 0 for v in identity.values())
                and identity['device'] == source['device'] and identity['inode'] != source['inode'])
        expected = {**identity, 'bytes': len(target), 'sha256': sha(target)}
        if arm is None:
            require(done is None and active == source and pending is not None
                    and {k: pending[k] for k in identity} == identity and target.startswith(raw))
            return 'SEEDED', owner, pending
        require(arm == {'owner': owner, 'source': source, 'target': expected})
        receipt = {'owner': owner, 'armed_sha256': sha(canonical_bytes(arm))}
        require(done is None or done == receipt)
        if active == expected:
            require(pending is None)
            return 'DONE' if done else 'RENAMED', owner, expected
        require(done is None and active == source and pending == expected)
        return 'ARMED', owner, expected

    def _rows(self, journal, plan):
        rows = []; pending = False
        for index, name in enumerate(self.replacements):
            state, _, _ = self._observe(journal, plan, index, name)
            require(not pending or state == 'PENDING', 'GATEWAY_PUBLIC_FRAGMENT_ORDER_CHANGED')
            if state != 'DONE': pending = True
            rows.append({'resource': name, 'state': state})
        return rows

    def check(self):
        with self._slot() as (fd, plan): rows = self._rows(fd, plan)
        return {'policy': POLICY, 'plan_sha256': sha(canonical_bytes(plan)), 'fragments': rows,
                'state': 'FRAGMENTS_REPLACED' if all(r['state'] == 'DONE' for r in rows) else 'INCOMPLETE',
                'services_started': False, 'systemd_reloaded': False,
                'activity_resumed': False, 'boot_requalified': False, 'phase6_complete': False}

    def replace_next(self, *, confirmation, confirmed):
        require(confirmed is True, 'GATEWAY_PUBLIC_CONSENT_REQUIRED'); self._held()
        with self._slot() as (journal, plan):
            require(type(confirmation) is str and confirmation == sha(canonical_bytes(plan)),
                    'GATEWAY_PUBLIC_CONFIRMATION_REQUIRED')
            rows = self._rows(journal, plan)
            for index, row in enumerate(rows):
                if row['state'] != 'DONE': break
            else: return self.check()
            name = row['resource']; target = self.replacements[name][1]
            state, owner, identity = self._observe(journal, plan, index, name)
            with self._parent(name, plan) as (fd, leaf):
                temporary = self._temporary(leaf)
                if state == 'PENDING':
                    self._held()
                    handle = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL
                                     | os.O_NOFOLLOW | os.O_CLOEXEC, 0o644, dir_fd=fd)
                    try:
                        os.fchmod(handle, 0o644); os.fsync(handle); os.fsync(fd)
                        identity = _identity(os.fstat(handle))
                        _put(journal, str(index) + '.seed.json', {'owner': owner, 'replacement': identity})
                    finally: os.close(handle)
                    state = 'SEEDED'
                if state == 'SEEDED':
                    _, _, pending = self._observe(journal, plan, index, name)
                    self._held()
                    handle = os.open(temporary, os.O_WRONLY | os.O_NOFOLLOW | os.O_CLOEXEC, dir_fd=fd)
                    try:
                        require(_identity(os.fstat(handle)) == {k: pending[k] for k in ('device', 'inode')})
                        os.lseek(handle, pending['bytes'], os.SEEK_SET)
                        files._write(handle, target[pending['bytes']:]); os.fsync(handle)
                    finally: os.close(handle)
                    expected, raw = _file(fd, temporary)
                    require(raw == target)
                    _put(journal, str(index) + '.armed.json', {'owner': owner,
                         'source': plan['sources'][name], 'target': expected})
                state, owner, _ = self._observe(journal, plan, index, name)
                if state == 'ARMED':
                    self._held()
                    os.rename(temporary, leaf, src_dir_fd=fd, dst_dir_fd=fd); os.fsync(fd)
                state, owner, _ = self._observe(journal, plan, index, name)
                require(state == 'RENAMED')
                self._held()
                arm = _optional(journal, str(index) + '.armed.json')
                _put(journal, str(index) + '.done.json', {'owner': owner,
                     'armed_sha256': sha(canonical_bytes(arm))})
        return self.check()
